export const initialNgos = [
  {
    id: 1,
    name: "Feeding Hands",
    email: "ngo@feedinghands.org",
    description: "Dedicated to eliminating child hunger and malnutrition across urban slum clusters in Mumbai through daily nutritious meal programs.",
    logo_emoji: "❤️",
    status: "ACTIVE",
    category: "Food",
    location: "Mumbai",
    founded_year: 2018,
    darpan_id: "MH/2018/0123456",
    trust_score: 95,
    hero_image_url: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&auto=format&fit=crop&q=80",
    website_url: "https://feedinghands.org",
    youtube_url: "https://youtube.com/@feedinghands",
    instagram_url: "https://instagram.com/feedinghands",
    donation_url: "https://feedinghands.org/donate",
    google_form_url: "https://forms.google.com/feeding-hands-volunteer",
    team_members: [
      { name: "Priya Sharma", role: "Founder & Director" },
      { name: "Rahul Deshmukh", role: "Field Coordinator" },
      { name: "Asha Nair", role: "Nutritionist" }
    ],
    funds_breakdown: { meals: 55, logistics: 20, raw_grain: 15, ops: 10 },
    score: 96.2,
    created_at: "2026-09-15"
  },
  {
    id: 2,
    name: "Women Shield",
    email: "contact@womenshield.org",
    description: "Empowering young girls and women survivors with legal aid, vocational skills, trauma counseling, and micro-entrepreneurship incubators.",
    logo_emoji: "🛡️",
    status: "ACTIVE",
    category: "Women",
    location: "Hyderabad",
    founded_year: 2019,
    darpan_id: "TS/2019/0458921",
    trust_score: 94,
    hero_image_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1200&auto=format&fit=crop&q=80",
    website_url: "https://womenshield.org",
    youtube_url: "https://youtube.com/@womenshield",
    instagram_url: "https://instagram.com/womenshield",
    donation_url: "https://womenshield.org/donate",
    google_form_url: "https://forms.google.com/womenshield-volunteer",
    team_members: [
      { name: "Sunita Reddy", role: "Legal Advocate" },
      { name: "Meena Rao", role: "Skill Development Lead" }
    ],
    funds_breakdown: { legal_aid: 40, vocational_kits: 35, counseling: 15, ops: 10 },
    score: 94.8,
    created_at: "2026-08-20"
  },
  {
    id: 3,
    name: "Vidya Jyoti Foundation",
    email: "info@vidyajyoti.org",
    description: "Setting up digital learning labs and after-school STEM tuition pods in rural government schools across Pune and Satara districts.",
    logo_emoji: "📚",
    status: "ACTIVE",
    category: "Education",
    location: "Pune",
    founded_year: 2016,
    darpan_id: "MH/2016/0098432",
    trust_score: 91,
    hero_image_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&auto=format&fit=crop&q=80",
    website_url: "https://vidyajyoti.org",
    youtube_url: "https://youtube.com/@vidyajyoti",
    instagram_url: "https://instagram.com/vidyajyoti",
    donation_url: "https://vidyajyoti.org/donate",
    google_form_url: "https://forms.google.com/vidyajyoti-teach",
    team_members: [
      { name: "Dr. Arvind Joshi", role: "Founder" },
      { name: "Kavita Shinde", role: "Curriculum Head" }
    ],
    funds_breakdown: { tablets_books: 50, teacher_stipend: 30, electricity_wifi: 10, ops: 10 },
    score: 92.1,
    created_at: "2026-07-10"
  },
  {
    id: 4,
    name: "Arogya Bharat Trust",
    email: "help@arogyabharat.org",
    description: "Mobile medical dispensaries providing preventive health screenings, free generic medicines, and pediatric care in tribal belts.",
    logo_emoji: "🩺",
    status: "ACTIVE",
    category: "Health",
    location: "Nagpur",
    founded_year: 2020,
    darpan_id: "MH/2020/0334120",
    trust_score: 93,
    hero_image_url: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=1200&auto=format&fit=crop&q=80",
    website_url: "https://arogyabharat.org",
    youtube_url: "https://youtube.com/@arogyabharat",
    instagram_url: "https://instagram.com/arogyabharat",
    donation_url: "https://arogyabharat.org/donate",
    google_form_url: "https://forms.google.com/arogya-medical-camps",
    team_members: [
      { name: "Dr. Sneha Kulkarni", role: "Chief Medical Officer" },
      { name: "Amit Verma", role: "Logistics Manager" }
    ],
    funds_breakdown: { medicines: 50, mobile_van_fuel: 25, doctor_stipends: 15, ops: 10 },
    score: 91.5,
    created_at: "2026-06-12"
  },
  {
    id: 5,
    name: "Prakriti Sanrakshan",
    email: "green@prakriti.org",
    description: "Urban afforestation and Miyawaki native forests creation to revitalize groundwater tables and reduce urban heat islands.",
    logo_emoji: "🌱",
    status: "ACTIVE",
    category: "Environment",
    location: "Bengaluru",
    founded_year: 2021,
    darpan_id: "KA/2021/0812940",
    trust_score: 89,
    hero_image_url: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&auto=format&fit=crop&q=80",
    website_url: "https://prakriti.org",
    youtube_url: "https://youtube.com/@prakritigreen",
    instagram_url: "https://instagram.com/prakritigreen",
    donation_url: "https://prakriti.org/donate",
    google_form_url: "https://forms.google.com/prakriti-plant-trees",
    team_members: [
      { name: "Karthik Subramanian", role: "Ecologist & Lead" },
      { name: "Divya Nambiar", role: "Community Volunteer Lead" }
    ],
    funds_breakdown: { saplings_soil: 50, drip_irrigation: 25, maintenance: 15, ops: 10 },
    score: 89.4,
    created_at: "2026-05-04"
  },
  {
    id: 6,
    name: "Jeev Daya Kendra",
    email: "care@jeevdaya.org",
    description: "Emergency stray animal rescue, round-the-clock veterinary ambulance, and cruelty prevention rehabilitation center.",
    logo_emoji: "🐾",
    status: "ACTIVE",
    category: "Animals",
    location: "Ahmedabad",
    founded_year: 2017,
    darpan_id: "GJ/2017/0219483",
    trust_score: 90,
    hero_image_url: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=1200&auto=format&fit=crop&q=80",
    website_url: "https://jeevdaya.org",
    youtube_url: "https://youtube.com/@jeevdaya",
    instagram_url: "https://instagram.com/jeevdaya",
    donation_url: "https://jeevdaya.org/donate",
    google_form_url: "https://forms.google.com/jeevdaya-volunteer",
    team_members: [
      { name: "Bhavin Shah", role: "Rescue Coordinator" },
      { name: "Dr. Riddhi Mehta", role: "Senior Vet" }
    ],
    funds_breakdown: { animal_food: 40, surgeries_meds: 35, shelter_care: 15, ops: 10 },
    score: 88.9,
    created_at: "2026-04-18"
  },
  {
    id: 7,
    name: "Umeed Foundation",
    email: "contact@umeed.org",
    description: "Providing shelter, rehabilitation, and education for runaway and street-connected youth.",
    logo_emoji: "✨",
    status: "PENDING",
    category: "Education",
    location: "Delhi",
    founded_year: 2022,
    darpan_id: "DL/2022/0778899",
    trust_score: 82,
    hero_image_url: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80",
    website_url: "https://umeed.org",
    youtube_url: "",
    instagram_url: "https://instagram.com/umeeddelhi",
    donation_url: "https://umeed.org/donate",
    google_form_url: "https://forms.google.com/umeed-volunteer",
    team_members: [
      { name: "Farhan Ali", role: "Founder" }
    ],
    funds_breakdown: { food_shelter: 60, books: 30, ops: 10 },
    score: 81.0,
    created_at: "2026-10-02"
  }
];

export const initialPosts = [
  {
    id: 1,
    title: "Food Drive in Dharavi Slums",
    summary: "500 nutritious hot meals distributed to daily-wage families and children.",
    raw_input: "We distributed 500 hot nutritious meals to sanitation workers and daily-wage families in Dharavi slums on Sunday morning with 30 passionate youth volunteers.",
    category: "Food",
    impact_count: 500,
    funds_goal: 50000,
    funds_raised: 37500,
    volunteers_needed: 10,
    media_urls: [
      "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=800&auto=format&fit=crop&q=80"
    ],
    status: "COMPLETED",
    event_date: "2026-10-01",
    is_top_needed: 1,
    ngo_id: 1
  },
  {
    id: 2,
    title: "Emergency Winter Blankets & Warm Rations",
    summary: "Urgent drive to distribute heavy blankets and dry food rations before cold wave hits.",
    raw_input: "Temperatures are dropping rapidly. Over 300 homeless elders need warm winter bedding and 15-day ration packages immediately across central shelters.",
    category: "Food",
    impact_count: 350,
    funds_goal: 75000,
    funds_raised: 42000,
    volunteers_needed: 15,
    media_urls: [
      "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop&q=80"
    ],
    status: "ONGOING",
    event_date: "2026-10-05",
    is_top_needed: 1,
    ngo_id: 1
  },
  {
    id: 3,
    title: "Self-Defense & Digital Safety Camp",
    summary: "Training 200 adolescent girls in cyber safety, POSH awareness, and martial defense.",
    raw_input: "Conducted an intensive 2-day self-defense camp and digital privacy workshop in Old Hyderabad government high school for 200 girl students.",
    category: "Women",
    impact_count: 200,
    funds_goal: 30000,
    funds_raised: 30000,
    volunteers_needed: 5,
    media_urls: [
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80"
    ],
    status: "COMPLETED",
    event_date: "2026-09-28",
    is_top_needed: 0,
    ngo_id: 2
  },
  {
    id: 4,
    title: "50 STEM Science Kits for Zilla Parishad School",
    summary: "Providing hands-on robotic & physics experiential learning kits for 350 rural pupils.",
    raw_input: "Setting up our third rural science discovery lab with 50 interactive STEM experiment kits, microscope sets, and solar kits in Velhe block.",
    category: "Education",
    impact_count: 350,
    funds_goal: 60000,
    funds_raised: 45000,
    volunteers_needed: 8,
    media_urls: [
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80"
    ],
    status: "ONGOING",
    event_date: "2026-10-10",
    is_top_needed: 1,
    ngo_id: 3
  },
  {
    id: 5,
    title: "Free Eye Checkup & Cataract Surgery Drive",
    summary: "Screening 400 rural elders and sponsoring 45 cataract operations with local hospital.",
    raw_input: "Mobile optical team screened 400 tribal elders in Melghat; identified 45 severe cataract cases and arranged surgical transfers with partner ophthalmic trust.",
    category: "Health",
    impact_count: 400,
    funds_goal: 90000,
    funds_raised: 55000,
    volunteers_needed: 12,
    media_urls: [
      "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&auto=format&fit=crop&q=80"
    ],
    status: "UPCOMING",
    event_date: "2026-10-18",
    is_top_needed: 1,
    ngo_id: 4
  },
  {
    id: 6,
    title: "Miyawaki Forest Plantation: 1,000 Native Trees",
    summary: "Planting a bio-diverse urban forest along dry lake buffer zone with citizen volunteers.",
    raw_input: "Joined by 120 citizen volunteers on Sunday morning to plant 1,000 native saplings (Neem, Peepal, Jamun, Mahua) using the dense Miyawaki methodology.",
    category: "Environment",
    impact_count: 1200,
    funds_goal: 40000,
    funds_raised: 40000,
    volunteers_needed: 25,
    media_urls: [
      "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800&auto=format&fit=crop&q=80"
    ],
    status: "COMPLETED",
    event_date: "2026-09-22",
    is_top_needed: 0,
    ngo_id: 5
  },
  {
    id: 7,
    title: "Stray Dog Vaccination & Anti-Rabies Drive",
    summary: "Vaccinated 150 community strays and distributed reflective safety collars against night traffic.",
    raw_input: "Our paramedic team safely captured, vaccinated, dewormed, and collared 150 stray dogs in satellite areas of Ahmedabad to stop rabies spread.",
    category: "Animals",
    impact_count: 150,
    funds_goal: 25000,
    funds_raised: 18000,
    volunteers_needed: 6,
    media_urls: [
      "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&auto=format&fit=crop&q=80"
    ],
    status: "COMPLETED",
    event_date: "2026-09-18",
    is_top_needed: 0,
    ngo_id: 6
  }
];
