server.port=8080

spring.datasource.url=jdbc:mysql://acmwork-atharvaghag800-42e5.l.aivencloud.com:14091/defaultdb?useSSL=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_nCW79Q6chmycvuVEV1h
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect